import { defineConfig } from 'vite-plus'

export default defineConfig({
  lint: {
    plugins: ['typescript', 'unicorn', 'oxc'],
    ignorePatterns: ['**/dist/**', 'convex/_generated/**'],
    overrides: [
      {
        files: [
          'frontend/**/*.ts',
          'frontend/**/*.tsx',
          'tests/ui/**/*.ts',
          'tests/ui/**/*.tsx',
        ],
        plugins: ['typescript', 'react'],
        env: { browser: true },
        rules: {
          'for-direction': 'error',
          'no-async-promise-executor': 'error',
          'no-case-declarations': 'error',
          'no-compare-neg-zero': 'error',
          'no-cond-assign': 'error',
          'no-constant-binary-expression': 'error',
          'no-constant-condition': 'error',
          'no-control-regex': 'error',
          'no-debugger': 'error',
          'no-delete-var': 'error',
          'no-dupe-else-if': 'error',
          'no-duplicate-case': 'error',
          'no-empty': 'error',
          'no-empty-character-class': 'error',
          'no-empty-pattern': 'error',
          'no-empty-static-block': 'error',
          'no-ex-assign': 'error',
          'no-extra-boolean-cast': 'error',
          'no-fallthrough': 'error',
          'no-global-assign': 'error',
          'no-invalid-regexp': 'error',
          'no-irregular-whitespace': 'error',
          'no-loss-of-precision': 'error',
          'no-misleading-character-class': 'error',
          'no-nonoctal-decimal-escape': 'error',
          'no-prototype-builtins': 'error',
          'no-regex-spaces': 'error',
          'no-self-assign': 'error',
          'no-shadow-restricted-names': 'error',
          'no-sparse-arrays': 'error',
          'no-unexpected-multiline': 'error',
          'no-unsafe-finally': 'error',
          'no-unsafe-optional-chaining': 'error',
          'no-unused-labels': 'error',
          'no-unused-private-class-members': 'error',
          'no-useless-backreference': 'error',
          'no-useless-catch': 'error',
          'no-useless-escape': 'error',
          'require-yield': 'error',
          'use-isnan': 'error',
          'valid-typeof': 'error',
          'no-var': 'error',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
          'typescript/ban-ts-comment': 'error',
          'typescript/no-duplicate-enum-values': 'error',
          'typescript/no-empty-object-type': 'error',
          'typescript/no-explicit-any': 'error',
          'typescript/no-extra-non-null-assertion': 'error',
          'typescript/no-misused-new': 'error',
          'typescript/no-namespace': 'error',
          'typescript/no-non-null-asserted-optional-chain': 'error',
          'typescript/no-require-imports': 'error',
          'typescript/no-this-alias': 'error',
          'typescript/no-unnecessary-type-constraint': 'error',
          'typescript/no-unsafe-declaration-merging': 'error',
          'typescript/no-unsafe-function-type': 'error',
          'typescript/no-wrapper-object-types': 'error',
          'typescript/prefer-as-const': 'error',
          'typescript/prefer-namespace-keyword': 'error',
          'typescript/triple-slash-reference': 'error',
          'react/rules-of-hooks': 'error',
          'react/exhaustive-deps': 'warn',
          'react/static-components': 'error',
          'react/use-memo': 'error',
          'react/preserve-manual-memoization': 'error',
          'react/incompatible-library': 'warn',
          'react/immutability': 'error',
          'react/globals': 'error',
          'react/refs': 'error',
          'react/set-state-in-effect': 'error',
          'react/error-boundaries': 'error',
          'react/purity': 'error',
          'react/set-state-in-render': 'error',
          'react/unsupported-syntax': 'warn',
          'no-array-constructor': 'error',
          'no-unused-expressions': 'error',
          'no-unused-vars': 'error',
        },
      },
    ],
  },
  fmt: {
    singleQuote: true,
    semi: false,
    sortImports: false,
    sortPackageJson: false,
    sortTailwindcss: {
      stylesheet: './frontend/src/index.css',
    },
    ignorePatterns: ['**/dist/**', 'convex/_generated/**', 'bun.lock'],
    overrides: [
      {
        files: ['server/package.json', 'server/tsconfig.json'],
        options: { tabWidth: 4 },
      },
    ],
  },
  test: {
    environment: 'node',
    globals: true,
    include: ['tests/convex/**/*.test.ts'],
    setupFiles: ['tests/convex/setup.ts'],
    restoreMocks: true,
    clearMocks: true,
    server: {
      deps: {
        inline: ['convex-test'],
      },
    },
  },
})
