import type { ActivityDefinition } from '../types'

export const scrapeRelationships: ActivityDefinition = {
  id: 'scrape_relationships',
  name: 'Scrape Relationships',
  description:
    'Open each target profile, click followers or following in the logged-in browser session, then inject JavaScript to scrape the selected relationship list.',
  category: 'browsing',
  icon: 'Search',
  color: '#F59E0B',
  inputs: [
    {
      name: 'kind',
      type: 'select',
      label: 'Relationship Type',
      default: 'followers',
      options: [
        { label: 'Followers', value: 'followers' },
        { label: 'Following', value: 'following' },
      ],
      group: 'Targets',
    },
    {
      name: 'targets',
      type: 'string_list',
      label: 'Target Usernames',
      required: true,
      default: [],
      placeholder: 'instagram\nnatgeo\nnasa',
      helpText: 'One username per line. The node runs each target sequentially.',
      group: 'Targets',
    },
    {
      name: 'chunkLimit',
      type: 'number',
      label: 'Chunk Limit',
      default: 200,
      min: 1,
      max: 5000,
      helpText: 'Maximum number of rows to request per browser-side page.',
      group: 'Pagination',
    },
    {
      name: 'maxPagesPerAttempt',
      type: 'number',
      label: 'Max Pages Per Attempt',
      default: 3,
      min: 1,
      max: 100,
      helpText: 'Limits how much one attempt will fetch before yielding to retry/resume state.',
      group: 'Pagination',
    },
    {
      name: 'maxAttempts',
      type: 'number',
      label: 'Max Attempts',
      default: 4,
      min: 1,
      max: 20,
      helpText: 'Retries transient failures before the node fails.',
      group: 'Retries',
    },
    {
      name: 'retryBackoffSeconds',
      type: 'string',
      label: 'Retry Backoff Seconds',
      default: '30,120,600,1800',
      placeholder: '30,120,600,1800',
      helpText: 'Comma-separated retry delays used for transient failures.',
      group: 'Retries',
    },
    {
      name: 'openDelaySeconds',
      type: 'number',
      label: 'Open Delay Seconds',
      default: 2,
      min: 0,
      max: 60,
      helpText: 'Wait time after opening a target profile before clicking the relationship link and injecting the scrape logic.',
      group: 'Retries',
    },
  ],
  outputs: ['success', 'failure'],
  pythonHandler: 'browsing.scrape_relationships',
}
