import type { ActivityDefinition } from '../types'

/**
 * Warm Up Activity
 *
 * Scrolls through the Instagram home feed to warm up the account.
 * Settings mirror: FeedSettingsDialog
 */
export const browseFeed: ActivityDefinition = {
  id: 'browse_feed',
  quickAdd: true,
  pickerGroup: 'browsing',
  keywords: ['warm', 'warm up', 'feed', 'scroll'],
  name: 'Warm Up',
  description: 'Scroll the home feed to warm up the account',
  category: 'browsing',
  icon: 'Scroll',
  color: '#3b82f6',

  inputs: [
    // Warm-up plan: minutes assigned at random from this range each day
    {
      name: 'warmup_min_minutes',
      type: 'number',
      label: 'Min Minutes',
      default: 30,
      min: 1,
      max: 100,
      group: 'Daily Budget',
      helpText: 'Lower bound of the daily assigned time.',
    },
    {
      name: 'warmup_max_minutes',
      type: 'number',
      label: 'Max Minutes',
      default: 60,
      min: 1,
      max: 100,
      group: 'Daily Budget',
      helpText: 'Upper bound of the daily assigned time.',
    },

    {
      name: 'session_min_minutes', type: 'number', label: 'Min Minutes',
      default: 5, min: 1, max: 60, group: 'Session Duration',
      helpText: 'Each session is capped by the remaining daily budget.',
    },
    {
      name: 'session_max_minutes', type: 'number', label: 'Max Minutes',
      default: 10, min: 1, max: 60, group: 'Session Duration',
    },
    {
      name: 'rest_min_minutes', type: 'number', label: 'Min Minutes',
      default: 60, min: 1, max: 1440, group: 'Rest Between Sessions',
    },
    {
      name: 'rest_max_minutes', type: 'number', label: 'Max Minutes',
      default: 120, min: 1, max: 1440, group: 'Rest Between Sessions',
      helpText: 'This profile rests between sessions while the automation runs other eligible profiles.',
    },

    // Engagement chances
    {
      name: 'like_chance',
      type: 'range',
      label: 'Like Chance',
      default: 10,
      min: 0,
      max: 100,
      unit: '%',
      group: 'Engagement',
    },

    // Follow Chance
    {
      name: 'follow_chance',
      type: 'range',
      label: 'Follow Chance',
      default: 0,
      min: 0,
      max: 100,
      unit: '%',
      group: 'Engagement',
    },

    // Carousel Watch Chance
    {
      name: 'carousel_watch_chance',
      type: 'range',
      label: 'Carousel Watch Chance',
      default: 0,
      min: 0,
      max: 100,
      unit: '%',
      group: 'Engagement',
    },

    // Carousel Max Slides
    {
      name: 'carousel_max_slides',
      type: 'number',
      label: 'Carousel Max Slides',
      default: 3,
      min: 1,
      max: 10,
      group: 'Carousel',
    },
    {
      name: 'watch_stories',
      type: 'boolean',
      label: 'Watch Stories Before Feed',
      default: false,
      helpText: 'Open the stories tray before warm up starts.',
      group: 'Stories',
    },
    {
      name: 'stories_max',
      type: 'number',
      label: 'Max Stories',
      default: 3,
      min: 1,
      max: 50,
      group: 'Stories',
    },
    {
      name: 'stories_min_view_seconds',
      type: 'number',
      label: 'Min View',
      default: 2,
      min: 0,
      step: 0.1,
      unit: 'sec',
      group: 'Story View Timing',
    },
    {
      name: 'stories_max_view_seconds',
      type: 'number',
      label: 'Max View',
      default: 5,
      min: 0,
      step: 0.1,
      unit: 'sec',
      group: 'Story View Timing',
    },
    {
      name: 'skip_post_chance',
      type: 'range',
      label: 'Skip Post Chance',
      default: 30,
      min: 0,
      max: 100,
      unit: '%',
      group: 'Skipping',
    },
    {
      name: 'skip_post_max',
      type: 'number',
      label: 'Max Posts to Skip',
      default: 2,
      min: 1,
      max: 10,
      group: 'Skipping',
    },
    {
      name: 'post_view_min_seconds',
      type: 'number',
      label: 'Min View',
      default: 2,
      min: 0,
      step: 0.1,
      unit: 'sec',
      group: 'Post View Timing',
    },
    {
      name: 'post_view_max_seconds',
      type: 'number',
      label: 'Max View',
      default: 5,
      min: 0,
      step: 0.1,
      unit: 'sec',
      group: 'Post View Timing',
    },
    {
      name: 'profile_visit_chance',
      type: 'range',
      label: 'Profile Visit Chance',
      default: 35,
      min: 0,
      max: 100,
      unit: '%',
      group: 'Explore',
      helpText: 'Sometimes open the author or a liker profile, look around, then return to feed.',
    },
    {
      name: 'liked_profile_visit_chance',
      type: 'range',
      label: 'Liked Post Visit Chance',
      default: 80,
      min: 0,
      max: 100,
      unit: '%',
      group: 'Explore',
      helpText: 'Chance to visit the author profile after liking their post.',
    },
    {
      name: 'own_profile_chance',
      type: 'range',
      label: 'Own Profile Chance',
      default: 10,
      min: 0,
      max: 100,
      unit: '%',
      group: 'Explore',
      helpText: 'Sometimes open your own profile from the sidebar, look around, then return.',
    },
    {
      name: 'dm_chance',
      type: 'range',
      label: 'DM Check Chance',
      default: 8,
      min: 0,
      max: 100,
      unit: '%',
      group: 'Explore',
      helpText: 'Sometimes open DMs from the sidebar, glance at the inbox, then go to feed or own profile.',
    },
    {
      name: 'reels_chance',
      type: 'range',
      label: 'Reels Chance',
      default: 12,
      min: 0,
      max: 100,
      unit: '%',
      group: 'Explore',
      helpText: 'Sometimes open Reels from the sidebar, watch a few, then return to feed.',
    },
    {
      name: 'reels_min',
      type: 'number',
      label: 'Min Reels',
      default: 3,
      min: 1,
      group: 'Explore',
    },
    {
      name: 'reels_max',
      type: 'number',
      label: 'Max Reels',
      default: 8,
      min: 1,
      group: 'Explore',
    },
    {
      name: 'reels_skip_chance',
      type: 'range',
      label: 'Reels Skip Chance',
      default: 25,
      min: 0,
      max: 100,
      unit: '%',
      group: 'Explore',
      helpText: 'Sometimes flick past a reel without watching it.',
    },
  ],

  outputs: ['success', 'failure'],
}


